defaults:  
  - _self_  
  # - override hydra/hydra_logging: colorlog  
  # - override hydra/job_logging: colorlog
  - override hydra/job_logging: custom

hydra:
  job:
    chdir: False
  run:
    dir: /tmp/${now:%Y-%m-%d_%H-%M-%S}
